# Generated by Django 4.2.6 on 2023-12-18 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 18, 8, 10, 54, 119452))),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='FrontStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_sale_end_date', models.DateTimeField(default=datetime.datetime(2023, 12, 18, 8, 10, 54, 118453))),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='store/slider')),
                ('slider_text', models.CharField(default='Upto 60% + Extra 10%', max_length=100)),
            ],
            options={
                'verbose_name': 'Front Store Settings',
                'verbose_name_plural': 'Front Store Settings',
                'db_table': 'storefront',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Blog')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 12, 18, 8, 10, 54, 119452))),
                ('published', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.blog')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
            },
        ),
    ]
