# Generated by Django 4.2.6 on 2023-12-18 16:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=100)),
                ('email_password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=50)),
                ('email_port', models.CharField(default=465, max_length=5)),
                ('use_tls', models.BooleanField(default=True)),
                ('fail_silently', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 16, 16, 32, 21695)),
        ),
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 16, 16, 32, 21695)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 16, 16, 32, 21695)),
        ),
    ]
