# Generated by Django 4.2.6 on 2023-12-19 18:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blog_date_created_alter_emailconfig_email_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Enter post content here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 18, 7, 41, 642268)),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='email_password',
            field=models.CharField(default='waxaaaofvxgifsyt', max_length=128, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='from_email',
            field=models.EmailField(default='bengomallKE@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 18, 7, 41, 641267)),
        ),
    ]
