# Generated by Django 4.2.6 on 2023-12-19 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blog_excerpt_alter_blog_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='Blog/featured'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 19, 21, 38, 73370)),
        ),
        migrations.AlterField(
            model_name='frontstore',
            name='flash_sale_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 19, 21, 38, 57788)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Blog/posts'),
        ),
    ]
