# Generated by Django 4.2.6 on 2023-12-18 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('box', models.CharField(default='00100-397', max_length=500)),
                ('street_or_road', models.CharField(default='Along Kisumu-Busia Road', max_length=255, verbose_name='Street/Road')),
                ('phone', models.CharField(blank=True, default='07000043578', max_length=15, null=True)),
                ('other_phone', models.CharField(blank=True, default='07000043578', max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Business Addresses',
                'db_table': 'business_addresses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('door_step_delivery', models.BooleanField(default=False)),
                ('door_step_delivery_charge', models.PositiveBigIntegerField(blank=True, default=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Regions',
                'db_table': 'delivery_regions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.ManyToManyField(to='human_resource.businessaddress')),
                ('delivery_regions', models.ManyToManyField(blank=True, null=True, to='human_resource.deliveryregions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PickupStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('open_hours', models.CharField(default='Mon-Fri 0800hrs - 1700hrs;Sat 0800hrs - 1300hrs', max_length=255)),
                ('payment_options', models.CharField(default='MPESA On Delivery, Cards', max_length=500)),
                ('google_pin', models.URLField(default='https://goo.gl/maps/p2QAwb7jbmxuJcb36', max_length=1500)),
                ('helpline', models.CharField(default='076353535353', max_length=20)),
                ('shipping_charge', models.PositiveBigIntegerField(default=85)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickupstations', to='human_resource.deliveryregions')),
            ],
            options={
                'verbose_name_plural': 'Pickup Stations',
                'db_table': 'pickup_stattions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10)),
                ('salary', models.PositiveIntegerField(default=1000)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_label', models.CharField(default='my address 1', max_length=255)),
                ('phone', models.CharField(blank=True, default='07000043578', max_length=15, null=True)),
                ('other_phone', models.CharField(blank=True, default='07000043578', max_length=15, null=True)),
                ('postal_code', models.CharField(blank=True, default='57-40100', max_length=100, null=True)),
                ('default_address', models.BooleanField(default=False, verbose_name='Default Address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='human_resource.pickupstations')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='human_resource.customer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='human_resource.deliveryregions')),
            ],
            options={
                'verbose_name_plural': 'AddressBook',
                'db_table': 'address_book',
                'managed': True,
            },
        ),
    ]
