# Generated by Django 4.2.6 on 2023-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanagement', '0002_delete_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_confirm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
