# Generated by Django 4.2.6 on 2023-12-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='644748', max_length=255)),
                ('checkoutid', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=1500)),
                ('status', models.CharField(default='success', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
