# Generated by Django 4.2.6 on 2023-12-18 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_level', models.PositiveIntegerField(default=1)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('usage', models.CharField(blank=True, choices=[('EX-UK', 'EX-UK'), ('Refurbished', 'Refurbished'), ('Used Like New', 'Used Like New'), ('Secod Hand', 'Second Hand'), ('New', 'New')], default='New', help_text='Leave blank if not applicable', max_length=20, null=True)),
                ('sku', models.CharField(default='1', max_length=100, unique=True)),
                ('serial', models.CharField(default='12263644', max_length=100, unique=True)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Re-Order', 'Re-Order')], default='In Stock', max_length=20)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_flash_sale', models.BooleanField(default=False)),
                ('is_deal_of_the_day', models.BooleanField(default=False)),
                ('is_top_pick', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.products')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize', verbose_name='Packaging')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='human_resource.supplier')),
            ],
            options={
                'verbose_name': 'Stock Inventory',
                'verbose_name_plural': 'Stock Inventory',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stockinventory.stockinventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
